### ISSUE TITLE
Printing recorder value in model run 

### ISSUE THREAD

**Issue by xoxshirl** [pywr/pywr#1081]
I have this recorder in my json model:

    "cost_objective": {
      "type": "aggregated",
      "recorder_agg_func": "sum",
      "recorders": [
        "total_normalised_capex",
        "total_opex"
      ],
      "is_objective": "minimise"
    },

and I would like to specifically print the outcome of this recorder value when loading and running my model in .py

**Comment by jetuk** [comment]
Try something like this:

```python
model.run()
obj = model.recorders["cost_objective"]
print(obj.aggregated_value())
```

**Comment by xoxshirl** [comment]
> Try something like this:
> 
> ```python
> model.run()
> obj = model.recorders["cost_objective"]
> print(obj.aggregated_value())
> ```

thanks, this is what i get now 

Exception has occurred: NotImplementedError
exception: no description
  File "/FILE_PATH/model_run.py", line 12, in <module>
    print(cost.aggregated_value())
NotImplementedError:

**Comment by jetuk** [comment]
Can you paste the full error message and/or the model definition? It might be an issue with the type of the two recorders your are aggregating.

**Comment by xoxshirl** [comment]
> Can you paste the full error message and/or the model definition? It might be an issue with the type of the two recorders your are aggregating.

Thank you, I am aggregating two aggregated recorders. 

here is the error message

my_model = Model.load('Thames_s3_additions.json')
Traceback (most recent call last):
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/lilliepeters/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/lilliepeters/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/lilliepeters/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/lilliepeters/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/lilliepeters/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/lilliepeters/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/lilliepeters/Documents/PhD/MODELLING TAKE 2/With additions/model_run.py", line 12, in <module>
    print(obj.aggregated_value())
  File "pywr/recorders/_recorders.pyx", line 331, in pywr.recorders._recorders.Recorder.aggregated_value
  File "pywr/recorders/_recorders.pyx", line 332, in pywr.recorders._recorders.Recorder.aggregated_value
  File "pywr/recorders/_recorders.pyx", line 415, in pywr.recorders._recorders.AggregatedRecorder.values
  File "pywr/recorders/_recorders.pyx", line 415, in pywr.recorders._recorders.AggregatedRecorder.values
  File "pywr/recorders/_recorders.pyx", line 336, in pywr.recorders._recorders.Recorder.values
NotImplementedError

**Comment by jetuk** [comment]
This is because "total_normalised_capex" and/or "total_opex" are of a recorder type that does not implement the `.values()` method. Are the custom recorders? If so they will need to implement that method and return an array of values equal in length to the number of scenarios in the model. If they are not custom recorders can you tell my what class/type they are?

**Comment by xoxshirl** [comment]
> This is because "total_normalised_capex" and/or "total_opex" are of a recorder type that does not implement the `.values()` method. Are the custom recorders? If so they will need to implement that method and return an array of values equal in length to the number of scenarios in the model. If they are not custom recorders can you tell my what class/type they are?

Ahh I see thank you. "total_normalised_capex" and "total_opex" are both aggregated recorders which have summed multiple parameter recorders which are constant values.

**Comment by jetuk** [comment]
OK! So, try using "NumpyArrayParameterRecorder" instead. You'll then need to specify the "temporal_agg_func" you would like on each those.

The "ParameterRecorder" is a sort of base class that doesn't do much on its own.

**Comment by xoxshirl** [comment]
> > This is because "total_normalised_capex" and/or "total_opex" are of a recorder type that does not implement the `.values()` method. Are the custom recorders? If so they will need to implement that method and return an array of values equal in length to the number of scenarios in the model. If they are not custom recorders can you tell my what class/type they are?
> 
> Ahh I see thank you. "total_normalised_capex" and "total_opex" are both aggregated recorders which have summed multiple parameter recorders which are constant values.

That's

> OK! So, try using "NumpyArrayParameterRecorder" instead. You'll then need to specify the "temporal_agg_func" you would like on each those.
> 
> The "ParameterRecorder" is a sort of base class that doesn't do much on its own.

That has done it! Amazing, thanks so much. :) much appreciated
