### ISSUE TITLE
help with scenarios! please

### ISSUE THREAD

**Issue by xoxshirl** [pywr/pywr#1093]
I cannot understand why my set up for a scenario is returning an error, any help appreciated

In my json file:

```json
"scenarios": [
{
  "name": "inflows",
  "size": 12,
  "slice": [0, 11]
}
],
"parameters": {
  "River:flow": {
    "type": "dataframe",
    "url": "River_scenarios.xlsx",
    "scenario": "inflows",
    "index_col": "0",
    "parse_dates": true,
    "comment": "units [ML/day]"
  },
```

my excel data as follows
<img width="1076" alt="River_scenarios" src="https://user-images.githubusercontent.com/126896906/235895076-9a4e04cc-d5a3-4012-8538-7e0d7e717561.png">

Error as follows :
ValueError: '0' is not in list

Thank you

**Comment by jetuk** [comment]
Can you paste the full traceback?

**Comment by xoxshirl** [comment]
> Can you paste the full traceback?

Error loading component __Days Weir__:flow
Traceback (most recent call last):
  File "/Users/lilliepeters/Documents/PhD/MODELLING TAKE 2/With additions/model_run.py", line 7, in <module>
    my_model = Model.load('Thames_s3_additions.json')
  File "pywr/_model.pyx", line 287, in pywr._model.Model.load
  File "pywr/_model.pyx", line 205, in pywr._model.Model.loads
  File "pywr/_model.pyx", line 295, in pywr._model.Model.load
  File "pywr/_model.pyx", line 421, in pywr._model.Model._load_from_dict
  File "pywr/_model.pyx", line 1016, in pywr._model.listify.wrapper
  File "pywr/_model.pyx", line 412, in load_components
  File "pywr/_model.pyx", line 408, in pywr._model.Model._load_from_dict.load_components
  File "pywr/parameters/_parameters.pyx", line 2159, in pywr.parameters._parameters.load_parameter
  File "pywr/parameters/_parameters.pyx", line 272, in pywr.parameters._parameters.DataFrameParameter.load
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pywr/dataframe_tools.py", line 178, in load_dataframe
    df = read_dataframe(model, data)
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pywr/dataframe_tools.py", line 261, in read_dataframe
    df = pandas.read_excel(url, **data)
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 465, in read_excel
    data = io.parse(
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1458, in parse
    return self._reader.parse(
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 715, in parse
    parser = TextParser(
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1350, in TextParser
    return TextFileReader(*args, **kwds)
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1235, in _make_engine
    return mapping[engine](f, **self.options)
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/python_parser.py", line 151, in __init__
    no_thousands_columns = self._set_noconvert_dtype_columns(
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 673, in _set_noconvert_dtype_columns
    noconvert_columns.add(_set(k))
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 650, in _set
    x = col_indices[names.index(x)]

**Comment by jetuk** [comment]
If the above does not work then try to load your data in pandas first. 

```python
df = pandas.read_excel("River_scenarios.xlsx", index_col=0, parse_dates=True)

print(df.index)
```

This should show the index is a `DatetimeIndex`. If it says something about an object then pandas has not managed to parse all of the dates correctly.

**Comment by xoxshirl** [comment]
> Try changing this
> 
> ```json
> "index_col": "0",
> ```
> 
> to this
> 
> ```json
> "index_col": 0,
> ```
> 
> Pandas is looking for a column with the name "0" instead of the zeroth column for your index.

yes unfortunately I've tried this but 

Traceback (most recent call last):
  File "/Users/lilliepeters/Documents/PhD/MODELLING TAKE 2/With additions/model_run.py", line 7, in <module>
    my_model = Model.load('Thames_s3_additions.json')
  File "pywr/_model.pyx", line 287, in pywr._model.Model.load
  File "pywr/_model.pyx", line 205, in pywr._model.Model.loads
  File "pywr/_model.pyx", line 295, in pywr._model.Model.load
  File "pywr/_model.pyx", line 421, in pywr._model.Model._load_from_dict
  File "pywr/_model.pyx", line 1016, in pywr._model.listify.wrapper
  File "pywr/_model.pyx", line 412, in load_components
  File "pywr/_model.pyx", line 408, in pywr._model.Model._load_from_dict.load_components
  File "pywr/parameters/_parameters.pyx", line 2159, in pywr.parameters._parameters.load_parameter
  File "pywr/parameters/_parameters.pyx", line 272, in pywr.parameters._parameters.DataFrameParameter.load
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pywr/dataframe_tools.py", line 178, in load_dataframe
    df = read_dataframe(model, data)
  File "/Users/lilliepeters/opt/anaconda3/lib/python3.9/site-packages/pywr/dataframe_tools.py", line 273, in read_dataframe
    raise TypeError(
TypeError: Invalid DataFrame index type "object" in "daysweir_scenarios.xlsx".

**Comment by jetuk** [comment]
This suggests there's an invalid date in the index. Can you double check the data? Is there a footer at the bottom or some missing values?

**Comment by xoxshirl** [comment]
> This suggests there's an invalid date in the index. Can you double check the data? Is there a footer at the bottom or some missing values?

I will check the data now, thank you

**Comment by xoxshirl** [comment]
Great, 0 instead of "0" and I had an extra day in April! thanks all.
