### ISSUE TITLE
install from source error - _DeprecatedInstaller: setuptools.installer

### ISSUE THREAD

**Issue by xoxshirl** [pywr/pywr#1116]
I am installing from source in develop mode and coming across this same error and cannot solve it and do not want to pip install as I want to add custom parameters, I am typing in the following command, python3 setup.py develop --with-glpk --without-lpsolve, but coming across this error, have multiple things but no luck: 

Traceback (most recent call last):
  File "/Users/.../pywr/setup.py", line 231, in <module>
    setup_package()
  File "/Users/.../pywr/setup.py", line 147, in setup_package
    setup(**metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 109, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 462, in __init__
    _Distribution.__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
    self.finalize_options()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 886, in finalize_options
    ep(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 907, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools_scm/_integration/setuptools.py", line 98, in version_keyword
    _assign_version(dist, config)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools_scm/_integration/setuptools.py", line 57, in _assign_version
    _version_missing(config)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools_scm/_get_version_impl.py", line 100, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /Users/.../pywr.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

**Comment by jetuk** [comment]
How did you download the Pywr source code? The error is from `setuptools-scm` which is expecting the source code to have been in a Git repository. I.e. you need to clone the git repository rather than download the source from Github.

**Comment by xoxshirl** [comment]
Ah ok so I downloaded as zip then unzipped, so cloning the git repository may solve this?

**Comment by xoxshirl** [comment]
Ok thanks, I think python3 setup.py develop --with-glpk is working now I've cloned instead of downloaded.  Hopefully will work.

**Comment by jetuk** [comment]
Yes, it should. This is used to figure out the version of Pywr from the Git tags. I guess we should handle this case with with an unknown version string.

**Comment by xoxshirl** [comment]
> Yes, it should. This is used to figure out the version of Pywr from the Git tags. I guess we should handle this case with with an unknown version string.

ok thank you, I cannot use --withoutlpsolve now so will have to sort that out now

**Comment by jetuk** [comment]
It should be `--without-lpsolve`. What error are you getting?

**Comment by xoxshirl** [comment]
That was it! Thank you.
