### ISSUE TITLE
Empty model gives non-descriptive error when run

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#346]
Should `model.check` raise an exception if the model is empty? Or should the solver have a protection in setup against models with no nodes?

```
>>> from pywr.model import Model
>>> model = Model()
>>> model.check()
>>> model.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/snorf/Desktop/pywr/pywr/model.py", line 471, in run
    self.setup()
  File "/Users/snorf/Desktop/pywr/pywr/model.py", line 502, in setup
    self.solver.setup(self)
  File "/Users/snorf/Desktop/pywr/pywr/solvers/__init__.py", line 42, in setup
    return self._cy_solver.setup(model)
  File "pywr/solvers/cython_glpk.pyx", line 60, in pywr.solvers.cython_glpk.CythonGLPKSolver.setup (pywr/solvers/cython_glpk.c:8903)
    cpdef object setup(self, model):
  File "pywr/solvers/cython_glpk.pyx", line 93, in pywr.solvers.cython_glpk.CythonGLPKSolver.setup (pywr/solvers/cython_glpk.c:4368)
    self.node_costs_arr = cvarray(shape=(self.num_nodes,), itemsize=sizeof(double), format="d")
  File "stringsource", line 151, in View.MemoryView.array.__cinit__ (pywr/solvers/cython_glpk.c:11262)
ValueError: Invalid shape in axis 0: 0.
```

**Comment by snorfalorpagus** [comment]
Closed by #354.
