### ISSUE TITLE
Circular dependency in parameter

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#560]
I'm getting this exception trying to import parameters with master. I'm guessing this is related to recent changes to the events code, but not sure.
```
(python36) C:\Project\pywr> python
Python 3.6.3 | packaged by conda-forge | (default, Oct  5 2017, 14:39:21) [MSC v.1900 64
 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywr.parameters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Project\pywr\pywr\parameters\__init__.py", line 1, in <module>
    from .parameters import *
  File "C:\Project\pywr\pywr\parameters\parameters.py", line 3, in <module>
    from ._parameters import (
  File "pywr\_core.pxd", line 4, in init pywr.parameters._parameters
    cdef class Scenario:
  File "pywr\recorders\_recorders.pxd", line 6, in init pywr._core
    cdef class Recorder(Component):
  File "C:\Project\pywr\pywr\recorders\__init__.py", line 1, in <module>
    from .recorders import *
  File "C:\Project\pywr\pywr\recorders\recorders.py", line 7, in <module>
    from .events import *
  File "C:\Project\pywr\pywr\recorders\events.py", line 2, in <module>
    from pywr.parameters import Parameter, IndexParameter
ImportError: cannot import name 'Parameter'
```

**Comment by snorfalorpagus** [comment]
This doesn't happen if `pywr.model` is imported first.

```
(python36) C:\Project\pywr> python
Python 3.6.3 | packaged by conda-forge | (default, Oct  5 2017, 14:39:21) [MSC v.1900 64
 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywr.model
>>> import pywr.parameters
```

**Comment by jetuk** [comment]
> I'm guessing this is related to recent changes to the events code, but not sure.

That's still not been merged. See #547.

**Comment by jetuk** [comment]
If you remove that particular example in `events.py` then you get another problem,
```
$ python3
Python 3.6.3 (default, Oct  9 2017, 12:07:10) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywr.parameters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/james/dev/pywr/pywr/parameters/__init__.py", line 1, in <module>
    from .parameters import *
  File "/home/james/dev/pywr/pywr/parameters/parameters.py", line 3, in <module>
    from ._parameters import (
  File "pywr/_core.pxd", line 4, in init pywr.parameters._parameters (pywr/parameters/_parameters.c:60670)
  File "pywr/recorders/_recorders.pxd", line 6, in init pywr._core (pywr/_core.c:46174)
  File "/home/james/dev/pywr/pywr/recorders/__init__.py", line 1, in <module>
    from .recorders import *
  File "/home/james/dev/pywr/pywr/recorders/recorders.py", line 8, in <module>
    from .calibration import *
  File "/home/james/dev/pywr/pywr/recorders/calibration.py", line 16, in <module>
    from pywr.parameters import align_and_resample_dataframe
ImportError: cannot import name 'align_and_resample_dataframe'
```

**Comment by jetuk** [comment]
I had to solve this in #328 to get the documentation to build correctly.

>$ python3 -c "import pywr.parameters"
>$
