### ISSUE TITLE
Better exceptions

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#673]
Generally we have some poor exception messages around the place.

An easy win here would be to make a better exception class for use during loading from JSON. This exception could contain the class/type object and name of the node/component that was trying to be loaded. This would be helpful for external applications to better highlight where the problem is.

#641 may make this easier.

**Comment by matrosoe** [comment]
There is an example of an error (the node and parameter are actually listed within the error)

```
Traceback (most recent call last):
File "pywr/_model.pyx", line 424, in pywr._model.Model._get_node_from_ref
File "pywr/_model.pyx", line 781, in pywr._model.NodeIterator.__getitem__
KeyError: "'Buywa_ Upper_contorl'"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/bin/hydra-pywr", line 11, in <module>
sys.exit(start_cli())
File "/usr/local/lib/python3.6/site-packages/hydra_pywr/cli.py", line 36, in start_cli
cli(obj={}, auto_envvar_prefix='HYDRA_PYWR')
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
return f(get_current_context().obj, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/hydra_pywr/cli.py", line 104, in run
run_network_scenario(client, network_id, scenario_id)
File "/usr/local/lib/python3.6/site-packages/hydra_pywr/cli.py", line 110, in run_network_scenario
runner.load_pywr_model()
File "/usr/local/lib/python3.6/site-packages/hydra_pywr/runner.py", line 45, in load_pywr_model
model = Model.load(pywr_data)
File "pywr/_model.pyx", line 378, in pywr._model.Model.load
File "pywr/_model.pyx", line 435, in pywr._model.Model._get_node_from_ref
File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 529, in load
postprocess=True,
File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 669, in _do_load
original_data=data,
File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 870, in _invoke_load_processors
data=data, many=many, original_data=original_data,
File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 1000, in _invoke_processors
data = processor(data)
File "/usr/local/lib/python3.6/site-packages/pywr/schema/__init__.py", line 60, in make_node
return klass(model, **non_param_data)
File "/usr/local/lib/python3.6/site-packages/pywr/nodes.py", line 114, in __call__
node = type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'release_values' 
```

**Comment by rheinheimer** [comment]
I would like to very strongly suggest better exception handling. At the very least, exceptions should be raised.  Here's the one I'm dealing with. For a custom parameter:
```python
def value(self, timestep, scenario_index):
    return "50.3"
```
This causes an error, `must be real number, not str`, but does not raise an exception. It just reports the issue, then ends. That's fine for one custom parameter. But if I have many (and I do), this is really, really painful to track down.

At the very least, it would be nice to be able to deal with this myself:
```python
    def value(self, timestep, scenario_index):
        try:
            return self._value(timestep, scenario_index)
        except Exception as err:
            print('ERROR for parameter {}'.format(self.name))
            print('File where error occurred: {}'.format(__file__))
            print(err)
            raise
```
Code ugliness aside, this works, when the error is in my own `self._value` function. However, I can't do anything if no exception is raised from Pywr...

**Comment by jetuk** [comment]
> This causes an error, must be real number, not str, but does not raise an exception.

This is actually a Cython thing in the value method. The function definition is below which means Cython will only test for exceptions if a -1 is returned. 

```
cpdef double value(self, Timestep ts, ScenarioIndex scenario_index) except? -1:
```

It could be changed to in which case an exception check is tested for each function call. We should test whether this has any major performance penalties before changing it though.

```
cpdef double value(self, Timestep ts, ScenarioIndex scenario_index) except *:
```
