### ISSUE TITLE
Dates far in the future break pandas.to_datetime

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#69]
`numpy.datetime64` is fine with these ranges if using a reasonable time step. Pandas is is limited to nanosecond resolution which limits flexibility.
```
>>> np.datetime64('4000-01-01')
numpy.datetime64('4000-01-01')
```
So I guess we can just use `datetime.date(time)` or `numpy.datetime64[D|m]` or a `pandas.Period`?

**Comment by snorfalorpagus** [comment]
`numpy.datetime64` seems more flexible with very, very large dates. I've recently been working with a 16000 year timeseries...

```
>>> np.datetime64('16000-01-01')
numpy.datetime64('16000-01-01')
```

```
>>> pandas.Period('16000-01-01')
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas/tseries/tools.py", line 488, in parse_time_string
    yearfirst=yearfirst)
  File "/usr/local/lib/python3.4/site-packages/pandas/tseries/tools.py", line 534, in dateutil_parse
    ret = default.replace(**repl)
ValueError: year is out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "das/src/period.pyx", line 702, in pandas._period.Period.__init__ (pandas/src/period.c:10296)
  File "/usr/local/lib/python3.4/site-packages/pandas/tseries/tools.py", line 491, in parse_time_string
    raise DateParseError(e)
pandas.tseries.tools.DateParseError: year is out of range
```

**Comment by jetuk** [comment]
So we should accept anything that `np.datetime64` can work with?

**Comment by snorfalorpagus** [comment]
OK. Let's move to `np.datetime64` and `np.timedelta64`, both internally and externally - cast the inputs if needed.

**Comment by jetuk** [comment]
We concluded here to use `np.datetime64` and not a `pandas.Period`. I like this idea better ... so much so that I forgot about it :)

**Comment by snorfalorpagus** [comment]
Sticking with `pandas.Timestamp`. See comment in #139.
