### ISSUE TITLE
Implementing pumping between two reservoirs

### ISSUE THREAD

**Issue by BaptisteFrancois** [pywr/pywr#696]
Hi - Pywr is great - thanks for developing this nice tool!

I am trying to implement a pumping policy between two reservoirs. 
Pumping rate depends on the gross head between the two reservoir levels. 
Following the example give here  #688 I wrote a new class 'PumpingPolicy'. 
However, when I load the json file, I got an error that says that PumpingPolicy is an "unknown parameter'

Here is my code:
```python
from pywr.core import Model
from pywr.parameters import Parameter

class PumpingPolicy(Parameter):
	def value(self, timestep, scenario_index):
		""" Calculate the gross Head between reservoir1 and reservoir2 """
		# Get the current level from the reservoir1 node and for this scenario_index
		current_level_reservoir1 = self.model.nodes['reservoir1'].level[scenario_index.global_id]
		# Get the current level from the reservoir2 node and for this scenario_index
		current_level_reservoir2 = self.model.nodes['reservoir2'].level[scenario_index.global_id]

		GrossHead_feet = current_level_reservoir1 - current_level_reservoir2
		
		if GrossHead_feet < 0: 
			Flow = -0.0172 * (-GrossHead_feet)**2 -2.6755 * (-GrossHead_feet) + 300.34
		else:
			Flow = 0
			
		return Flow
				
PumpingPolicy.register()
m = Model.load('../model/file.json')
```
Following the example given in the cooking book, it looks like I have to define a @classmethod.
However, having a very limited experience using class in python, I cannot figure out what is missing in here to be able to load this parameter from my json file. 

Also - the function 'PumpingPolicy' is supposed to return a single value for each time step to be used . Below is the json code I try to use to make this happen. Shall I just give 'PumpingPolicy' as 'max_flow' value for the considered link?

Thank you.

**Comment by snorfalorpagus** [comment]
Can you share the JSON document also?

Your equation for flow returns a negative value if `GrossHead_feet` ~< -76. All flows in Pywr should be >= 0. Is it your intention to have bidirectional flow, or is this a quirk of the equation?

Title case is normally reserved for class names, i.e. `flow` instead of `Flow` and `gross_head_feet` instead of `gross_head_feet`.

**Comment by jetuk** [comment]
@BaptisteFrancois in this case I do not think you need a `@classmethod` because your parameter does not have any custom inputs. If you could paste the JSON document (or snippet) that is trying to load define a instance of this parameter and also the traceback you have that would be good. 

My guess is that you are not creating an instance of your parameter in the "parameters" section of the JSON. Your JSON document should look something like this,

```json
{
"nodes": [
    {
        "name": "reservoir1",
        "type": "storage"
    },
    {
        "name": "reservoir2",
        "type": "storage"
    },
    {
        "name": "pump",
        "type": "link",
        "cost": -10,
        "max_flow": "pumping_policy1"
    }
],
"edges": [
  ...
],
"parameters": {
    "pumping_policy1": {
        "type": "PumpingPolicy"
    }
}
}

```
Note how you must define an instance of your policy in the parameter's section using a name (e.g. "pumping_policy1"). This is what you assign to the `max_flow` on the transferring link. You could then create a second instance of your policy for use on a second link if required.

**Comment by jetuk** [comment]
See also this example which is similar; two reservoirs with controlled pumping (but via a control curve).

https://github.com/pywr/pywr/blob/master/examples/two_reservoir.json

**Comment by BaptisteFrancois** [comment]
@snorfalorpagus  Thanks!
The gross head cannot be lower than -76, meaning that 'flow' cannot be negative.

I replaced Title case by lower case as suggested. Is this a constraint of the json format or just a convention?

@jetuk Thanks! in the parameter section.

I was indeed not using an intance in the parameters' section.
Here is my updated python script:
```python
import os, glob
from pywr.core import Model
from pywr.parameters import Parameter

class PumpingPolicy(Parameter):

	def value(self, timestep, scenario_index):

		# Get the current level from the reseroir1 node and for this scenario_index
		current_level_reservoir1 = self.model.nodes['reservoir1'].level[scenario_index.global_id]
		
		# Get the current level from the reervoir2 node and for this scenario_index
		current_level_reservoir2 = self.model.nodes['reservoir2'].level[scenario_index.global_id]

		GrossHead_feet = current_level_reservoir1 - current_level_reservoir2
		
		
		# If GrossHead_feet < 0 
		# Pumping(5pumps) = -0.0172 * (-GrossHead_feet)**2 -2.6755 * (-GrossHead_feet) + 300.34
		if gross_head_feet < 0: 
			pump_ch_2_el = -0.0172 * (-gross_head_feet)**2 -2.6755 * (-gross_head_feet) + 300.34
		
		else:
			pump_ch_2_el = 0
			
		return pump_ch_2_el
		
PumpingPolicy.register()

m = Model.load('../model/test.json')
```

My json file is attached

```json
{
	"metadata":{
		"title": "test",
		"description": "Water resource system model for test",
		"author": "Baptiste Francois - bfrancois@umass.edu"
	},
	"timestepper": {
		"start":"1920-01-01",
		"end": "2010-12-31",
		"timestep": 7
	},
	"nodes": [
		{
			"name": "catchment_1",
			"type": "catchment",
			"flow": {
				"type": "dataframe",
				"url": "../data/streamflow/inflow1.csv",
				"column": "flow",
				"index_col": "Date",
				"parse_dates": true
			}
		},
		{
			"name": "catchment_2",
			"type": "catchment",
			"flow": {
				"type": "dataframe",
				"url": "../data/streamflow/inflow2.csv",
				"column": "flow",
				"index_col": "Date",
				"parse_dates": true
			}
		},
		{
			"name": "reservoir1",
			"type": "storage",
			"max_volume": {
				"type": "monthlyprofile",
				"url": "../data/reservoir/Smax_ControlCurve.csv",
				"index_col": "Reservoir",
				"index":"res1"
			},
			"min_volume": 0,
			"initial_volume": 10
		},
		{
			"name": "reservoir2",
			"type": "storage",
			"max_volume": {
				"type": "monthlyprofile",
				"url": "../data/reservoir/Smax_ControlCurve.csv",
				"index_col": "Reservoir",
				"index":"res2"
			},
			"min_volume": 1000,
			"initial_volume": 1500
		},
		{
			"name": "pump_ch_2_el",
			"type": "link",
			"cost": -10,
			"max_flow": "pumping_policy_ch_2_el"
		}
	],
	"edges": [
		["catchment_1",  "reservoir1"],
		["reservoir1",   "pump_ch_2_el"],
		["catchment_2",  "reservoir2"],
		["pump_ch_2_el", "reservoir2"]
	],
	"parameters":{
		"pumping_policy_ch_2_el":{
			"type": "PumpingPolicy"
		}
	},
	"recorders": {
		"pumping_ch_2_el_rec": {
			"type": "numpyarraynoderecorder",
			"node": "pump_ch_2_el"
		}
	}
}
```

The error I got now is:
```
test.py:30: ModelDocumentWarning: Missing "minimum_version" item in metadata.
  m = Model.load('../model/test.json')
Traceback (most recent call last):
  File "pywr\_model.pyx", line 413, in pywr._model.Model._get_node_from_ref
  File "pywr\_model.pyx", line 765, in pywr._model.NodeIterator.__getitem__
KeyError: "'pump_ch_2_el'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 30, in <module>
    m = Model.load('../model/test.json')
  File "pywr\_model.pyx", line 257, in pywr._model.Model.load
  File "pywr\_model.pyx", line 191, in pywr._model.Model.loads
  File "pywr\_model.pyx", line 376, in pywr._model.Model.load
  File "pywr\recorders\_recorders.pyx", line 1388, in pywr.recorders._recorders.load_recorder
  File "pywr\recorders\_recorders.pyx", line 182, in pywr.recorders._recorders.Recorder.load
  File "pywr\_model.pyx", line 419, in pywr._model.Model._get_node_from_ref
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\pywr\nodes.py", line 182, in load
    max_flow = load_parameter(model, max_flow)
  File "pywr\parameters\_parameters.pyx", line 1402, in pywr.parameters._parameters.load_parameter
  File "pywr\parameters\_parameters.pyx", line 1433, in pywr.parameters._parameters.load_parameter
  File "pywr\parameters\_parameters.pyx", line 116, in pywr.parameters._parameters.Parameter.load
  File "pywr\parameters\_parameters.pyx", line 1476, in pywr.parameters._parameters.load_parameter_values
ValueError: Parameter ('None' of type 'None' is missing a valid key to load its values. Please provide either a 'values', 'url' or 'table' entry.

```

**Comment by jetuk** [comment]
> I replaced Title case by lower case as suggested. Is this a constraint of the json format or just a convention?

@snorfalorpagus was giving you style suggestions for the Python code. If you get really nerdy you can read PEP8: https://www.python.org/dev/peps/pep-0008/

However, you should definitely be using 4 spaces instead of tabs for Python code.

I think your error is actually caused by a lack of the `@classmethod` - the one I said you didn't need! The default assumes there is a "value" or "values" key, and your class does not need that.

I think you need a trivial method like so to make this work - sorry I haven't tested this.

```python
import os, glob
from pywr.core import Model
from pywr.parameters import Parameter

class PumpingPolicy(Parameter):
    def value(self, timestep, scenario_index):

        # Get the current level from the reseroir1 node and for this scenario_index
        current_level_reservoir1 = self.model.nodes['reservoir1'].level[scenario_index.global_id]
        
        # Get the current level from the reervoir2 node and for this scenario_index
        current_level_reservoir2 = self.model.nodes['reservoir2'].level[scenario_index.global_id]

        GrossHead_feet = current_level_reservoir1 - current_level_reservoir2


        # If GrossHead_feet < 0 
        # Pumping(5pumps) = -0.0172 * (-GrossHead_feet)**2 -2.6755 * (-GrossHead_feet) + 300.34
        if gross_head_feet < 0: 
            pump_ch_2_el = -0.0172 * (-gross_head_feet)**2 -2.6755 * (-gross_head_feet) + 300.34
        else:
            pump_ch_2_el = 0
		return pump_ch_2_el

    @classmethod
    def load(cls, model, data):
        return cls(model, **data)

```

**Comment by BaptisteFrancois** [comment]
This is great - Thank you. 
The JSON file is loading correctly.

**Comment by BaptisteFrancois** [comment]
Hi, 
I am again running into an issue. It looks like via the custom class 'PumpingPolicy' I do not correctly read the water level of reseroir1. 
Below is the Traceback

``` python 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywr\_model.pyx", line 551, in pywr._model.Model.step
  File "pywr\_model.pyx", line 554, in pywr._model.Model._step
  File "pywr\_model.pyx", line 667, in pywr._model.Model.before
  File "pywr\parameters\_parameters.pyx", line 53, in pywr.parameters._parameters.Parameter.calc_values
  File "pywr\parameters\_parameters.pyx", line 45, in pywr.parameters._parameters.Parameter.value
  File "SFPUC_pywr_UpCountry.py", line 51, in value
    current_level_reservoir1 = self.model.nodes['reservoir1'].level[scenario_index.global_id]
TypeError: 'float' object is not subscriptable
```

My reservoir level parameter is:
``` json
"reservoir1_level":{
			"type": "interpolatedvolume",
			"node": "reservoir1",
			"volumes": [0, 75, 250, 675, 1530, 3025, 6030, 11745, 19740, 28885, 38886, 49751, 60836, 72701, 85131, 98111, 111811, 125681, 139921, 154586, 169691, 185196, 201096, 217371, 234076, 251231, 268811, 277879, 286947],
			"values": [4440, 4450, 4460, 4470, 4480, 4490, 4500, 4510, 4520, 4530, 4540, 4550, 4560, 4570, 4580, 4590, 4600, 4610, 4620, 4630, 4640, 4650, 4660, 4670, 4680, 4690, 4700, 4705, 4710],
			"kind": "cubic"
		},
```

Any thoughts?

**Comment by jetuk** [comment]
Try this:

```python
current_level_reservoir1 = self.model.nodes['reservoir1'].get_level(scenario_index)
current_level_reservoir2 = self.model.nodes['reservoir2'].get_level(scenario_index)
```
I see the inconsistency between how we access volumes and levels here. We should add a `get_volume(scenario_index)` method.

**Comment by BaptisteFrancois** [comment]
Thanks. 
It looks now that I have an issue with the Type of the values to be interpolated.

```json
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywr\_model.pyx", line 579, in pywr._model.Model.run
  File "pywr\_model.pyx", line 554, in pywr._model.Model._step
  File "pywr\_model.pyx", line 667, in pywr._model.Model.before
  File "pywr\parameters\_parameters.pyx", line 53, in pywr.parameters._parameters.Parameter.calc_values
  File "pywr\parameters\_parameters.pyx", line 45, in pywr.parameters._parameters.Parameter.value
TypeError: must be real number, not NoneType
```

**Comment by jetuk** [comment]
Ah this was also my fault. Notice how the indentation of the parameter was incorrect around the "return" statement. See this version instead. It should return a number at all times now.

```python
import os, glob
from pywr.core import Model
from pywr.parameters import Parameter

class PumpingPolicy(Parameter):
    def value(self, timestep, scenario_index):

        # Get the current level from the reseroir1 node and for this scenario_index
        current_level_reservoir1 = self.model.nodes['reservoir1'].level[scenario_index.global_id]
        
        # Get the current level from the reervoir2 node and for this scenario_index
        current_level_reservoir2 = self.model.nodes['reservoir2'].level[scenario_index.global_id]

        GrossHead_feet = current_level_reservoir1 - current_level_reservoir2


        # If GrossHead_feet < 0 
        # Pumping(5pumps) = -0.0172 * (-GrossHead_feet)**2 -2.6755 * (-GrossHead_feet) + 300.34
        if gross_head_feet < 0: 
            pump_ch_2_el = -0.0172 * (-gross_head_feet)**2 -2.6755 * (-gross_head_feet) + 300.34
        else:
            pump_ch_2_el = 0
        return pump_ch_2_el

    @classmethod
    def load(cls, model, data):
        return cls(model, **data)
```

**Comment by BaptisteFrancois** [comment]
Great, thanks!
