### ISSUE TITLE
Failed to use csv file to define 'volume' and 'values

### ISSUE THREAD

**Issue by BaptisteFrancois** [pywr/pywr#698]

**Comment by BaptisteFrancois** [comment]
Here is my json file I try to use to interpolate the water level from a reservoir from the volume:

```json
"parameters": {
		"cherry_level":{
			"type": "interpolatedvolume",
			"node": "eleanor_reservoir",
			"volumes": {
				"type": "dataframe",
				"url": "../data/reservoir/Storage_Elev_Cherry_4.csv",
				"column": "Storage_ACF",
				"parse_dates": false
			},
			"values": {
				"type": "dataframe",
				"url": "../data/reservoir/Storage_Elev_Cherry_4.csv",
				"column": "Elev_FEET",
				"parse_dates": false
			},
			"kind": "cubic"
		}.
       ......
```

When using this code, I am getting the error below:
```python
(wrs) C:\Users\bfrancois\Documents\11_Tools\WRS_pywr\SanFrancisco\script>python -i SFPUC_pywr_UpCountry.py
SFPUC_pywr_UpCountry.py:81: UnutilisedDataWarning: Model ends before the end of the DataFrame. Some data is not used.
  stats = m.run()
Traceback (most recent call last):
  File "SFPUC_pywr_UpCountry.py", line 81, in <module>
    stats = m.run()
  File "pywr\_model.pyx", line 572, in pywr._model.Model.run
  File "pywr\_model.pyx", line 621, in pywr._model.Model.setup
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\pywr\parameters\parameters.py", line 73, in setup
    self.interp = interp1d(self.x, self.y, **self.interp_kwargs)
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\scipy\interpolate\interpolate.py", line 433, in __init__
    _Interpolator1D.__init__(self, x, y, axis=axis)
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\scipy\interpolate\polyint.py", line 60, in __init__
    self._set_yi(yi, xi=xi, axis=axis)
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\scipy\interpolate\polyint.py", line 124, in _set_yi
    if xi is not None and shape[axis] != len(xi):
TypeError: len() of unsized object
>>>
```

However, if I hard code 'volume' and 'values' array in the json file, I do not get the error:
``` json
"parameters": {
		"cherry_level":{
			"type": "interpolatedvolume",
			"node": "eleanor_reservoir",
			"volumes": [0, 6030, 11745, 85131, 268811, 277879],
			"values": [0, 8, 973, 1211, 1515, 1792],
			"kind": "cubic"
		},
....
```

My question is then; can we define 'volumes' and 'values' array from a csv file?
Thank you,
B.

**Comment by jetuk** [comment]
@BaptisteFrancois it looks like defining "volumes" and "values" is not supported via a file. This can probably be fixed quite easily. Is it a big issue for your model?

**Comment by BaptisteFrancois** [comment]
@jetuk thanks!
For now I can hard code these volume - elevation curves in my json model. 
But maybe this could be an easy enhancement for the next update of pywr.
