### ISSUE TITLE
Error when loading a parameter (bug?)

### ISSUE THREAD

**Issue by BaptisteFrancois** [pywr/pywr#711]
Hello,
I almost spent the afternoon looking for solving this issue but I could not figure it out. 
Basically, I am just defining and 'area' parameter as an interpolatedvolume. For some reason, this imports failed. 
See below a simplified json file where I reproduce the error, and the trailback of the error.
```json
{
	"metadata":{
		"title": "test"
	},
	"timestepper": {
		"start":"2100-07-01",
		"end": "2149-06-30",
		"timestep": 1
	},
	"nodes": [
	{
		"name": "san_andreas_reservoir",
		"type": "storage",
		"max_volume": 19000.0,
		"min_volume": 3137.0,
		"initial_volume": 15000.0,
		"area": "san_andreas_area",
		"cost": -1
	}
	],
	"parameters": {
		"san_andreas_area": {
			"type": "interpolatedvolume",
			"node": "san_andreas_reservoir",
			"volumes": [0, 55.15, 450.83, 1559.67, 3289.01, 5771.95, 8947.01, 12680.16, 17116.98, 21223.97],
			"values": [0, 15.3, 63.0, 136.6, 202.3, 277.0, 341.4, 401.0, 477.4, 543.1],
			"kind": "cubic"
		}
	}
}
```
Trailback

```python
Traceback (most recent call last):
  File "pywr\_model.pyx", line 413, in pywr._model.Model._get_node_from_ref
  File "pywr\_model.pyx", line 765, in pywr._model.NodeIterator.__getitem__
KeyError: "'san_andreas_reservoir'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pywr\parameters\_parameters.pyx", line 1399, in pywr.parameters._parameters.load_parameter
KeyError: 'san_andreas_area'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywr\_model.pyx", line 257, in pywr._model.Model.load
  File "pywr\_model.pyx", line 191, in pywr._model.Model.loads
  File "pywr\_model.pyx", line 382, in pywr._model.Model.load
  File "pywr\parameters\_parameters.pyx", line 1433, in pywr.parameters._parameters.load_parameter
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\pywr\parameters\parameters.py", line 115, in load
    node = model._get_node_from_ref(model, data.pop("node"))
  File "pywr\_model.pyx", line 419, in pywr._model.Model._get_node_from_ref
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\pywr\nodes.py", line 428, in load
    area = load_parameter(model, area)
  File "pywr\parameters\_parameters.pyx", line 1401, in pywr.parameters._parameters.load_parameter
KeyError: "Unknown parameter: 'san_andreas_area'"
```

any help would be really appreciated!
Thank you,
Baptiste

**Comment by jetuk** [comment]
@BaptisteFrancois this is a known issue with a circular reference when loading parameters - see https://github.com/pywr/pywr/issues/380 for the original report and also #641 is the eventual branch that will fix this.

For now the workaround is to define the parameter inline on the node:

```
{
	"metadata":{
		"title": "test"
	},
	"timestepper": {
		"start":"2100-07-01",
		"end": "2149-06-30",
		"timestep": 1
	},
	"nodes": [
	{
		"name": "san_andreas_reservoir",
		"type": "storage",
		"max_volume": 19000.0,
		"min_volume": 3137.0,
		"initial_volume": 15000.0,
		"area": {
			"type": "interpolatedvolume",
			"node": "san_andreas_reservoir",
			"volumes": [0, 55.15, 450.83, 1559.67, 3289.01, 5771.95, 8947.01, 12680.16, 17116.98, 21223.97],
			"values": [0, 15.3, 63.0, 136.6, 202.3, 277.0, 341.4, 401.0, 477.4, 543.1],
			"kind": "cubic"
		},
		"cost": -1
	}
	]
}
```

**Comment by BaptisteFrancois** [comment]
@jetuk it works. Thanks!

**Comment by BaptisteFrancois** [comment]
A following question. 
When we define the area within the node description, rather than as a parameter, how can I use the actual value of the area in the description of another parameter; for instance an aggregated parameter that would multiply the area by an evaporation rate?
Thanks.

**Comment by jetuk** [comment]
I think you can give it a name key as part of its definition:  `"name": "my parameter"`

**Comment by BaptisteFrancois** [comment]
It works!
Thanks once more.

**Comment by BaptisteFrancois** [comment]
HI,
I have to reopen this issue.
After having done some modifications of the model, the area parameter for at least one does not load anymore. Note that the modifications I have made are not directly related to this reservoir and its area parameter.

I tried to load the area parameter from the 'parameters' section of the json file and/or directly from the attribute of the node. In both cases, the import failed and return the error ''KeyError: "unknown parameter:  'reservoir_area' "

Any help or workaround would be really appreciated.
Thank you.

**Comment by jetuk** [comment]
Can you provide a cut down version of a model that experiences this problem?

**Comment by BaptisteFrancois** [comment]
Hi, 
Sorry for being so long to answer. Several things kept me away from Github ... 

Unfortunatelty, it is difficult to cut down the model to little piece .. .

However, I have just realized that, while the model run with no problem, I got the 'parameter unknown' error for the 'reservoir_area' parameter (which is defined within the storage node declaration) when I want to output evaporation (using a recorder).

Maybe that can help you to further solve the issue. 
B.

**Comment by jetuk** [comment]
Can you give me the full traceback of the error? It fails when you include a recorder for the area in your model? I do wonder if this is the same circular dependency issue.

**Comment by BaptisteFrancois** [comment]
Below is the full traceback

```python
` (wrs)` F:\SFPUC_Pywr\script>python -i SFWSM_Validation_Historical.py

Traceback (most recent call last):
  File "pywr\_model.pyx", line 413, in pywr._model.Model._get_node_from_ref
  File "pywr\_model.pyx", line 765, in pywr._model.NodeIterator.__getitem__
KeyError: "'evap_don_pedro'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pywr\parameters\_parameters.pyx", line 1399, in pywr.parameters._parameters.load_parameter
KeyError: 'don_pedro_area'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SFWSM_Validation_Historical.py", line 4757, in <module>
    m = Model.load(model)
  File "pywr\_model.pyx", line 257, in pywr._model.Model.load
  File "pywr\_model.pyx", line 191, in pywr._model.Model.loads
  File "pywr\_model.pyx", line 376, in pywr._model.Model.load
  File "pywr\recorders\_recorders.pyx", line 1388, in pywr.recorders._recorders.load_recorder
  File "pywr\recorders\_recorders.pyx", line 182, in pywr.recorders._recorders.Recorder.load
  File "pywr\_model.pyx", line 419, in pywr._model.Model._get_node_from_ref
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\pywr\nodes.py", line 182, in load
    max_flow = load_parameter(model, max_flow)
  File "pywr\parameters\_parameters.pyx", line 1402, in pywr.parameters._parameters.load_parameter
  File "pywr\parameters\_parameters.pyx", line 1433, in pywr.parameters._parameters.load_parameter
  File "pywr\parameters\_parameters.pyx", line 1007, in pywr.parameters._parameters.AggregatedParameter.load
  File "pywr\parameters\_parameters.pyx", line 1401, in pywr.parameters._parameters.load_parameter
KeyError: "Unknown parameter: 'don_pedro_area'"
``
It fails when I include a recorder for the evaporation node. The evaporation node is a link with max_flow attribute being a parameter defined within the parameter section. This parameter is an aggregated parameter (agg_func: product) that multiplies that reservoir area (defined within the node section, i.e., within the storage node declaration) that is defined as an interpolatedvolume parameter, with a dataframe parameter that gives ET over the lake.

What is interesting is that w/out the parameter, the model runs w/out any problem. When I try to use the evaporation over the lake to calculate the value of another parameter (basically to calculate a fraction of the evaporation), it fails as well returning the same error 'don_pedro_area' unknown parameter.

**Comment by jetuk** [comment]
Can you try defining everything in the "parameters" section? I don't think you will need to set the area in attribute of the reservoir node.

**Comment by BaptisteFrancois** [comment]
I tried but if I do so, the model does not run and return an 'unknonwn parameter area' when calculating the evaporation (product of the reservoir area and an evaporation rate defined in a dataframe parameter).

**Comment by jetuk** [comment]
> product of the reservoir area and an evaporation rate defined in a dataframe parameter

Is this a custom parameter?

Instead of using the reservoir area directly, make it use a parameter and give it the area parameter. I wonder if you can avoid using the area property of the reservoir itself. 

I am finding this difficult to debug/help you without an example.

**Comment by BaptisteFrancois** [comment]
Okay - so here is the reservoir node and the evaporation node.
```json
{
			"name": "don_pedro_reservoir",
			"type": "storage",
			"max_volume": 2030000,
			"initial_volume": 1690000,
			"area": {
				"name": "don_pedro_area",
				"type": "interpolatedvolume",
				"node": "don_pedro_reservoir",
				"volumes":[0, 35, 120, 229, 383, 617, 916, 1280, 1759, 2401, 3268, 4481, 6283, 8906, 12393, 16706, 21899, 28101, 35404, 44037, 54237, 66110, 79744, 95337, 113313, 134591, 158731, 184827, 212870, 242866, 274760, 308960, 345310, 384060, 425510, 469910, 517450, 568150, 621950, 678950, 738950, 802500, 869700, 940700, 1015700, 1094900, 1178300, 1266400, 1359200, 1457100, 1560300, 1669000, 1783300, 1903600, 2030000],
				"values": [0, 7, 10, 12, 19, 28, 32, 41, 55, 74, 100, 144, 219, 308, 391, 473, 567, 675, 787, 942, 1100, 1250, 1480, 1640, 1960, 2300, 2530, 2690, 2920, 3080, 3300, 3520, 3750, 4000, 4290, 4590, 4920, 5220, 5540, 5840, 6180, 6530, 6900, 7300, 7710, 8130, 8570, 9030, 9530, 10050, 10590, 11150, 11720, 12330, 12960],
				"kind": "cubic"
			},
			"cost": -2
		},
		{
			"name": "evap_don_pedro",
			"type": "output",
			"max_flow": "don_pedro_lake_evaporation",
			"cost": {
				"type": "constant",
				"url": "../../data/costs/Cost_Systemwide.csv",
				"index_col": "Category",
				"index": "EVAP",
				"column": "Cost"
			}
		},

```
(Parameter section) Below are the dataframe of evaporation rate and the aggregated parameter that multiplies the evap rate and the reservoir area.
```json
		"evaporation_don_pedro_ts": {
			"type": "dataframe",
			"url": "../../data/input_validation_HHLSM/PRECIP_EVAP_LAKE/PET_Res_S_P100T0_R1_UC_202010-207009.csv",
			"column": "pet_res_DP_ft",
			"index_col": "Date",
			"parse_dates": true
		},
		"don_pedro_lake_evaporation": {
			"type": "aggregated",
			"agg_func": "product",
			"parameters": [
				"don_pedro_area",
				"evaporation_don_pedro_ts"
			]
		},
```
The model works all good but when I try to use the node 'evap_don_pedro' as an ouput of a virtual storage, the model crashes with the error I mentioned in the previous posts:

```json

		{
			"name": "water_bank_reservoir",
			"type": "virtualstorage",
			"initial_volume": 570000,
			"max_volume": 570000,
			"nodes": [
				"total_don_pedro_inflow",
				"transer_district_waterbank",
				"district_right",
				"evap_don_pedro"
			],
			"factors": [
				-1.0,
				-1.0,
				1.0,
				1.0
			]
		},
```
Below, I copy the traceback of the error:
```python
  File "SFWSM_Validation_HHLSM.py", line 5711, in <module>
    m = Model.load(model)
  File "pywr\_model.pyx", line 257, in pywr._model.Model.load
  File "pywr\_model.pyx", line 191, in pywr._model.Model.loads
  File "pywr\_model.pyx", line 376, in pywr._model.Model.load
  File "pywr\recorders\_recorders.pyx", line 1388, in pywr.recorders._recorders.load_recorder
  File "pywr\recorders\_recorders.pyx", line 182, in pywr.recorders._recorders.Recorder.load
  File "pywr\_model.pyx", line 419, in pywr._model.Model._get_node_from_ref
  File "pywr\_core.pyx", line 1045, in pywr._core.AggregatedStorage.load
  File "pywr\_model.pyx", line 419, in pywr._model.Model._get_node_from_ref
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\pywr\nodes.py", line 502, in load
    nodes.append(model._get_node_from_ref(model, node_name))
  File "pywr\_model.pyx", line 419, in pywr._model.Model._get_node_from_ref
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\pywr\nodes.py", line 182, in load
    max_flow = load_parameter(model, max_flow)
  File "pywr\parameters\_parameters.pyx", line 1402, in pywr.parameters._parameters.load_parameter
  File "pywr\parameters\_parameters.pyx", line 1433, in pywr.parameters._parameters.load_parameter
  File "pywr\parameters\_parameters.pyx", line 1007, in pywr.parameters._parameters.AggregatedParameter.load
  File "pywr\parameters\_parameters.pyx", line 1401, in pywr.parameters._parameters.load_parameter
KeyError: "Unknown parameter: 'don_pedro_area'"

```

**Comment by jetuk** [comment]
@BaptisteFrancois I've had a look at this. I can see the issue is in fact #380. And happens because,

1. `don_pedro_area` parameter is needs to be defined the parameters section so it can be used by the evaporation calculation, 
2. `don_pedro_area` needs to be defined inline on the `area` key of the storage node to resolve the circular loading issue (i.e. it depends on the storage node itself). 

The only workaround I can suggest is something like the following. Abandon using the `area` attribute of the storage node all together and define all the parameters in the `"parameters"` section.  If you want to record the area just use a `ParameterRecorder` on `don_pedro_area` directly. 

I will add the broken (non-loading) approach as a test to Pywr if you don't mind. I will also check to see if it works on #641.

```json
{
    "metadata": {
        "title": "Issue 711",
        "description": "https://github.com/pywr/pywr/issues/711",
        "minimum_version": "1.1"
    },
    "timestepper": {
        "start": "2015-01-01",
        "end": "2015-12-31",
        "timestep": 1
    },
    "nodes": [
		{
			"name": "total_don_pedro_inflow",
			"type": "input"
		},
        {
			"name": "don_pedro_reservoir",
			"type": "storage",
			"max_volume": 2030000,
			"initial_volume": 1690000,
			"cost": -2
		},
		{
			"name": "evap_don_pedro",
			"type": "output",
			"max_flow": "don_pedro_lake_evaporation",
			"cost": -1000
		},
        {
			"name": "water_bank_reservoir",
			"type": "virtualstorage",
			"initial_volume": 570000,
			"max_volume": 570000,
			"nodes": [
				"total_don_pedro_inflow",
				"evap_don_pedro"
			],
			"factors": [
				-1.0,
				1.0
			]
		}
    ],
    "edges": [
        ["total_don_pedro_inflow", "don_pedro_reservoir"],
        ["don_pedro_reservoir", "evap_don_pedro"]
    ],
    "parameters": {
          "evaporation_don_pedro_ts": {
              "type": "constant",
              "value": 0
          },
          "don_pedro_lake_evaporation": {
              "type": "aggregated",
              "agg_func": "product",
              "parameters": [
                  "don_pedro_area",
                  "evaporation_don_pedro_ts"
              ]
          },
		  "don_pedro_area":	{
				"type": "interpolatedvolume",
				"node": "don_pedro_reservoir",
				"volumes":[0, 35, 120, 229, 383, 617, 916, 1280, 1759, 2401, 3268, 4481, 6283, 8906, 12393, 16706, 21899, 28101, 35404, 44037, 54237, 66110, 79744, 95337, 113313, 134591, 158731, 184827, 212870, 242866, 274760, 308960, 345310, 384060, 425510, 469910, 517450, 568150, 621950, 678950, 738950, 802500, 869700, 940700, 1015700, 1094900, 1178300, 1266400, 1359200, 1457100, 1560300, 1669000, 1783300, 1903600, 2030000],
				"values": [0, 7, 10, 12, 19, 28, 32, 41, 55, 74, 100, 144, 219, 308, 391, 473, 567, 675, 787, 942, 1100, 1250, 1480, 1640, 1960, 2300, 2530, 2690, 2920, 3080, 3300, 3520, 3750, 4000, 4290, 4590, 4920, 5220, 5540, 5840, 6180, 6530, 6900, 7300, 7710, 8130, 8570, 9030, 9530, 10050, 10590, 11150, 11720, 12330, 12960],
				"kind": "cubic"
			}
    }
}
```
