### ISSUE TITLE
Pywr not running examples

### ISSUE THREAD

**Issue by richhay12** [pywr/pywr#801]
When I try to run any of the example Pywr problems, I am getting the following error, even on simple models.  Any ideas of what can cause this issue? 

Traceback (most recent call last):
  File "C:/Users/XXXXX/PycharmProjects/PywrProjects/PywrEx1.py", line 1, in <module>
    from pywr.core import Model, Input, Output
  File "C:\Users\XXXXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\pywr\core.py", line 5, in <module>
    from pywr.timestepper import Timestepper
  File "C:\Users\XXXXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\pywr\timestepper.py", line 4, in <module>
    from pywr import _core
  File "pywr\recorders\_recorders.pxd", line 6, in init pywr._core
  File "C:\Users\XXXXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\pywr\recorders\__init__.py", line 1, in <module>
    from .recorders import *
  File "C:\Users\XXXXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\pywr\recorders\recorders.py", line 5, in <module>
    from ._recorders import *
  File "pywr\parameters\_parameters.pxd", line 5, in init pywr.recorders._recorders
  File "C:\Users\XXXXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\pywr\parameters\__init__.py", line 1, in <module>
    from .parameters import *
  File "C:\Users\XXXXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\pywr\parameters\parameters.py", line 4, in <module>
    from ._parameters import (
  File "__init__.pxd", line 918, in init pywr.parameters._parameters
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by Batch21** [comment]
I also got this error recently and it seems to be a problem with numpy - https://github.com/numpy/numpy/issues/12785

Updating the version of numpy you are using should fix it.

**Comment by richhay12** [comment]
Thanks, James, that was part of the issue.  There were a couple of other packages that needed to be upgraded as well, but your suggestion put me on the right path!

**Comment by jetuk** [comment]
Sounds like this is resolved.
