### ISSUE TITLE
Cannot use VirtualStorage with a control curve parameter

### ISSUE THREAD

**Issue by rheinheimer** [pywr/pywr#826]
I am trying to rely on a virtual storage node in a control curve parameter. For example:
```
"New Melones Lake/Cost/1": {
            "type": "controlcurveinterpolated",
            "storage_node": "New Melones Lake/1",
            "control_curves": [
                "New Melones Lake/Storage Demand/1",
                0.2
            ],
            "values": [
                100,
                0.0,
                0.0,
                -1000.0
            ]
        },
```
where the `storage_node` in this case is a VirtualReservoir (the first control_curve element is a custom class). Should this be possible? I am getting a very not helpful error, but I've narrowed it down to this setup. When I use this with a real reservoir, it works fine.

**Comment by jetuk** [comment]
Can you paste the error message?

**Comment by rheinheimer** [comment]
The full message is quite long, pasted below. A couple things to note. 1. In no case am I missing a "type" (see last line below). 2. I don't know if it's relevant, but there is some possibly circular action, though I don't think it's actually circular: the virtual storage depends on a single link, whose cost depends on the virtual storage. i.e., in the JSON code above, `"New Melones Lake/Cost/1"` is for the link that `"New Melones Lake/1"` tracks for storage.

Here's the full error:
```python
Traceback (most recent call last):
  File "pywr\_model.pyx", line 417, in pywr._model.Model._get_node_from_ref
  File "pywr\_model.pyx", line 768, in pywr._model.NodeIterator.__getitem__
KeyError: "'New Melones Lake/1'"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "pywr\_model.pyx", line 417, in pywr._model.Model._get_node_from_ref
  File "pywr\_model.pyx", line 768, in pywr._model.NodeIterator.__getitem__
KeyError: "'New Melones Lake [link]/1'"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "pywr\_model.pyx", line 417, in pywr._model.Model._get_node_from_ref
  File "pywr\_model.pyx", line 768, in pywr._model.NodeIterator.__getitem__
KeyError: "'New Melones Lake/1'"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\david\Anaconda3\envs\waterlp-pywr2\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-d76ed5216bc2>", line 1, in <module>
    Model.load(planning_model_path, path=planning_model_path)
  File "pywr\_model.pyx", line 271, in pywr._model.Model.load
  File "pywr\_model.pyx", line 189, in pywr._model.Model.loads
  File "pywr\_model.pyx", line 385, in pywr._model.Model.load
  File "pywr\_model.pyx", line 904, in pywr._model.listify.wrapper
  File "pywr\_model.pyx", line 382, in load_components
  File "pywr\recorders\_recorders.pyx", line 1625, in pywr.recorders._recorders.load_recorder
  File "pywr\recorders\_recorders.pyx", line 223, in pywr.recorders._recorders.Recorder.load
  File "pywr\_model.pyx", line 423, in pywr._model.Model._get_node_from_ref
  File "C:\Users\david\Anaconda3\envs\waterlp-pywr2\lib\site-packages\pywr\nodes.py", line 485, in load
    nodes.append(model._get_node_from_ref(model, node_name))
  File "pywr\_model.pyx", line 423, in pywr._model.Model._get_node_from_ref
  File "C:\Users\david\Anaconda3\envs\waterlp-pywr2\lib\site-packages\pywr\nodes.py", line 179, in load
    cost = load_parameter(model, cost)
  File "pywr\parameters\_parameters.pyx", line 1538, in pywr.parameters._parameters.load_parameter
  File "pywr\parameters\_parameters.pyx", line 1558, in pywr.parameters._parameters.load_parameter
  File "pywr\parameters\_control_curves.pyx", line 298, in pywr.parameters._control_curves.ControlCurveInterpolatedParameter.load
  File "pywr\parameters\_control_curves.pyx", line 161, in pywr.parameters._control_curves.BaseControlCurveParameter._load_storage_node
  File "pywr\_model.pyx", line 421, in pywr._model.Model._get_node_from_ref
KeyError: 'type'
```

**Comment by rheinheimer** [comment]
Update: I'm thinking that quasi-circular thing is actually part of the problem, even though I think it's okay conceptually, and should ultimately work in Pywr. I'm looking at the load method in nodes.py:
```python
            del(data["type"])
            nodes = []
            for node_name in data.pop("nodes"):
                nodes.append(model._get_node_from_ref(model, node_name))
```
I'm thinking `del(data["type"])` removes `type` from the VirtualStorage node. Then, when loading the contributing node's cost during `model._get_node_from_ref(...)` above, `type` is not there in the VirtualStorage that cost depends on, since we've deleted it. If this analysis is correct, how to fix? Maybe make a deep copy of data before deleting `type`?

**Comment by jetuk** [comment]
This might be #380 (also in #711). The workaround is to define the parameter inline on the node (rather than in the parameters section) as per this comment: https://github.com/pywr/pywr/issues/711#issuecomment-484007728

Let me know if that helps.

**Comment by rheinheimer** [comment]
Yeah, okay. Thanks! I haven't tested it to see if it works, but assuming it will based on those issues.

In the meantime, I will probably also try to create a piecewise reservoir akin to PiecewiseLink.

**Comment by rheinheimer** [comment]
I think there would be two solutions to this:
1. Define cost in a custom parameter based on, say, last time step's elevation or, if needed, some estimation of the current time step's reservoir level.
2. PiecewiseStorage. I'm going to try this, as it is seems methodologically better.

**Comment by jetuk** [comment]
> Defining the control curve parameter directly within the object that needs it does NOT seem to work.

Is it the same error?

The example you give isn't what I thought actually. It would be a case where you are setting the `cost` of the `storage_node`. But here you are setting the cost of a different node. Is there a circular reference back to `New Melones Lake [link]/1` from `New Melones Lake/1`?

I'll try to take a look at this in more detail. It might be a different issue.

> Define cost in a custom Python parameter class based on, say, last time step's elevation

Isn't this what the current `controlcurveinterpolated` is doing?

> PiecewiseStorage. I'm going to try this, as it is seems methodologically better.

I would try doing this manually with many storage nodes with increasing costs firsts to see if it can works as you expect with the LP.
