### ISSUE TITLE
Running into an error when trying to run your two_reservoir_moea.py example

### ISSUE THREAD

**Issue by BaptisteFrancois** [pywr/pywr#963]
IHello,
I am interested into using moea with pywr but I can't get your example running. 

I am running the model as: ```  python -i two_reservoir_moea.py --harmonic --library platypus ```

Here is the error I am getting.

```
Traceback (most recent call last):
  File "C:\Users\bfrancois\Anaconda3\envs\emulator_wrs\lib\site-packages\pywr\optimisation\__init__.py", line 69, in _cached
    cache = MODEL_CACHE[self.uid]
KeyError: '7cb3f269b5e74f2fac953ff5ee599b65'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "two_reservoir_moea.py", line 201, in <module>
    platypus_main(harmonic=args.harmonic)
  File "two_reservoir_moea.py", line 40, in platypus_main
    wrapper = PlatypusWrapper(get_model_data(harmonic=harmonic))
  File "C:\Users\bfrancois\Anaconda3\envs\emulator_wrs\lib\site-packages\pywr\optimisation\platypus.py", line 31, in __init__
    m = self.model
  File "C:\Users\bfrancois\Anaconda3\envs\emulator_wrs\lib\site-packages\pywr\optimisation\__init__.py", line 84, in model
    return self._cached.model
  File "C:\Users\bfrancois\Anaconda3\envs\emulator_wrs\lib\site-packages\pywr\optimisation\__init__.py", line 71, in _cached
    model = self.make_model()
  File "C:\Users\bfrancois\Anaconda3\envs\emulator_wrs\lib\site-packages\pywr\optimisation\__init__.py", line 103, in make_model
    m = self.pywr_model_klass.load(self.pywr_model_json)
  File "pywr\_model.pyx", line 294, in pywr._model.Model.load
  File "pywr\_model.pyx", line 108, in pywr._model.Model.__init__
  File "pywr\_model.pyx", line 629, in pywr._model.Model.reset
  File "pywr\_model.pyx", line 697, in pywr._model.Model.flatten_component_tree
AttributeError: 'DiGraph' object has no attribute 'nodes_with_selfloops'
```

Any help would be appreciated.
Thanks in advance.
Baptiste

**Comment by jetuk** [comment]
What version of networkx are you using?

**Comment by jetuk** [comment]
I believe we fixed this issue here: https://github.com/pywr/pywr/issues/596

Which version of Pywr are you using? If it's an older version then it'll only work with older versions of networkx because of the deprecated function.
